### ISSUE TITLE
List the members of the batch (read BatchRegistry contract)

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch7.buidlguidl.com#3]
## Goal

Show the current members of your batch in the app.

- Show it on the main page or create a page (/builders) listing all the builders registered in the BatchRegistry contract (see #9)
- Each builder should link to their personal profile (see #8)

**Comment by fels21** [comment]
Can I be assigned to this issue?

**Comment by carletex** [comment]
Done @fels21 !
