### ISSUE TITLE
Get the check-in count from the BatchRegistry contract

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch7.buidlguidl.com#5]
## Goal

There is a "To Be implemented" string in `packages/nextjs/app/page.tsx` that should show the number of builders that have checked in to the contract.

We want to show the real count (reading from the BatchRegistry contract)

For more info about the contract: #9

**Comment by Ursulovic** [comment]
Can I get assigned to tihs?

**Comment by carletex** [comment]
Done @Ursulovic !
